services:
  workerbee:
    container_name: workerbee
    image: workerbee
    build: ./
    restart: always
    ports:
      - "8500:8080"
    depends_on:
      workerbee_database: 
        condition: service_healthy
    env_file:
      - .env
    mem_limit: 1g
    cpus: "2.0"

  workerbee_database:
    image: postgres:18-alpine
    container_name: workerbee_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      LOAD_DUMMY_DATA: ${LOAD_DUMMY_DATA}

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init.up.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./db/dummydata.sql:/dummydata.sql
      - ./db/dummydata.sh:/docker-entrypoint-initdb.d/02-load-dummy.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB}"]
      interval: 10s
      timeout: 10s
    mem_limit: 1g
    cpus: "2.0"

volumes:
  postgres_data:
